project:
  type: website

filters:
  - pyodide-interaktiv
  - math-exercise
  - py-exercise

website:
  title: "Matematikk 3A"
  sidebar:
    style: "docked"
    contents:
      - text: "IDE"
        file: pages/page1.qmd

      - section: "Flyttall og lineær algebra"
        contents:
          - pages/page2.qmd

      - section: "Projects"
        contents:
          - pages/project_week1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
