project:
  type: website

lang: nb

filters:
  - pyodide-interaktiv
  - jsxgraph
  - math-exercise
  - py-exercise

website:
  title: "Matematikk 3A"
  sidebar:
    style: "docked"
    contents:
      - text: "IDE / Readme"
        file: pages/page1.qmd

      - text: "Uke 1 – regnetid, binære tall og tall på datamaskiner"
        file: pages/page2.qmd

      - text: "Uke 2 – fikspunktiterasjon"
        file: pages/page4.qmd

      - section: "Projects"
        contents:
          - pages/project_week1.qmd
          - pages/project_week2.qmd

      - section: "Eksamensoppgaver"
        contents:
          - text: "Flyttall og numerisk stabilitet"
            file: pages/page5.qmd

format:
  html:
    theme: cosmo
    css: styles.css
