project:
  type: website

filters:
  - pyodide

website:
  title: "Matematikk 3A"
  sidebar:
    style: "docked"
    contents:
      - text: "Flyttall og lineær algebra"
        file: pages/page1.qmd

      - section: "Optimering"
        contents:
          - pages/page2.qmd
          
format:
  html:
    theme: cosmo
    css: styles.css