"""Export browser setup includes for use beside a downloaded notebook.

Run after editing a lecture or project setup include. Use --week 6 to
export only week 6; without arguments both week 6 and week 7 are exported.
"""
from pathlib import Path
import argparse
import re

ROOT = Path(__file__).resolve().parents[1]


def export_week(week):
    sources = [ROOT / f'_includes/linalg/week{week}_setup.md']
    if week == 6:
        sources.append(ROOT / '_includes/projects/week6_setup.md')
    blocks = []
    for source in sources:
        blocks.extend(re.findall(r'```\{pyodide-python\}\n(.*?)```', source.read_text(), re.S))
    code = '\n\n'.join('\n'.join(line for line in block.splitlines()
                                   if not line.startswith('#|')) for block in blocks)
    target = ROOT / f'assets/project_week{week}_setup.py'
    target.parent.mkdir(exist_ok=True)
    origins = ', '.join(str(source.relative_to(ROOT)) for source in sources)
    target.write_text(f'# Generated by scripts/export_project_setup.py from {origins}\n'
                      '# Requires NumPy and Matplotlib. No network access is needed.\n'+code+'\n')
    print(target.relative_to(ROOT))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--week', type=int, choices=(6, 7))
    args = parser.parse_args()
    for week in ((args.week,) if args.week else (6, 7)):
        export_week(week)
