"""Export the browser setup cells for use beside a downloaded notebook.

Run after editing either week6_setup.md or week7_setup.md.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
for week in (6, 7):
    source = ROOT / f'_includes/linalg/week{week}_setup.md'
    blocks = re.findall(r'```\{pyodide-python\}\n(.*?)```', source.read_text(), re.S)
    code = '\n\n'.join('\n'.join(line for line in block.splitlines()
                                   if not line.startswith('#|')) for block in blocks)
    target = ROOT / f'assets/project_week{week}_setup.py'
    target.parent.mkdir(exist_ok=True)
    target.write_text(f'# Generated by scripts/export_project_setup.py from {source.relative_to(ROOT)}\n'
                      '# Requires NumPy and Matplotlib. No network access is needed.\n'+code+'\n')
    print(target.relative_to(ROOT))
